### ISSUE TITLE
Does it need a second monitor,please?是否需要第二个屏幕？

### ISSUE THREAD

**Issue by IanZhang1991** [Bebove/macos-kvm#1]
I ma try this on my surface book 2, I just don't know is it possible.
我准备在我的笔记本上尝试，不知道是否需要第二个屏幕。

**Comment by cool-ic** [comment]
No need

**Comment by minhchau9999** [comment]
Hi,
Whenever I start my guest vm (MacOS), the monitor turns black and no input.
Any helps?
BR

**Comment by cool-ic** [comment]
maybe  your motherboard have a bad support for iommu
